# Generated by Django 2.1.5 on 2019-02-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='users',
        ),
    ]
